### PR TITLE
Support for entering concepts directly

### LINKED ISSUE #7: Pass inputs in readable format
Could be a game changer in usability to support passing data per concept and in a human-readable form, e.g.,:

```tex
\credit{Conceptualization}{Alice, Bob}
\credit{Data curation}{Charlie}
...
```

### PR DESCRIPTION
**Pull request by jannisborn**
Closes #7 

```tex

% New behavior
\credit{Alice}{Investigation, Methodology, Data curation, Writing -- original draft}
\credit{Bob}{Visualization,conceptualization}
\credit{Charlie}{Software,Writing -- review \& editing,Validation}
\insertcredits 
\insertcreditsstatement

% Old behavior
\credit{Alice}{1,0,0,0,0,0,0,0,0,0.8,0,0,1,1}
\credit{Eve}{0,1,1,0.2,1,1,0.8,1,1,1,1,1,0,0}
\insertcreditsgranular
\insertcreditsgranularstatement
```

### CODE REVIEW

**Comment by Pseudomanifold** [comment]
Looks good to me, but I think this should include an overhaul of the `example.tex` and `README.md`. I can do this but it will take me some days :-)

**Comment by jannisborn** [comment]
Think so too but no rush on that 👍🏼

**Comment by jannisborn** [comment]
@Pseudomanifold updated the README a bit to reflect the changes.

I also added a new command `\resetcredits` which resets all contributions, thus allowing to show two different blocks of contributions within the same doc

**Review by Pseudomanifold — APPROVED** [review]

**Comment by Pseudomanifold** [comment]
Looks very good to me! Thanks a lot, Jannis!

**Pull request merged**
